### PR TITLE
Add documentation about debugging with Docker

### PR DESCRIPTION
**Pull request by gaby**
* Add Docker debug instructions to README.md

Tools were mentioned in #77

### CODE REVIEW

**Comment by tooryx** [comment]
Hi @gaby,

Thank you for your contribution! Although, I would prefer to keep the default container image as lightweight as possible. Maybe we could add some instructions in the README instead to help people debug these situations.

Let me know your thoughts, otherwise I will close this PR after some time.

_~tooryx_

**Comment by gaby** [comment]
@tooryx The problem is without some of those tools in the image you will need to build your own tsunami container for debugging. 

I could probably remove vi and iproute

**Comment by tooryx** [comment]
Could you not just inject yourself inside the container?

```
$ docker run -d --rm  --network="host" --name=tsunami -v "$(pwd)/logs":/usr/tsunami/logs frakman1/tsunami:latest --ip-v4-target=172.17.0.2
xxxxxxxx # the container id
$ docker exec -it tsunami bash
# apt update && apt install -y vi {...}
```

**Comment by gaby** [comment]
@tooryx Yes that will work as long as you have internet access.

Adding a note to the readme should be enough. I will change the PR later today after work

**Comment by tooryx** [comment]
Thank you!

**Comment by gaby** [comment]
@tooryx Done, I tried to keep simple and concise

**Review by tooryx — COMMENTED** [review]
Thank you @gaby! I added a small note

**Comment by gaby** [comment]
@tooryx Done

**Pull request merged**
